env: UpkieGroundVelocity-v1
gin:
    EnvSettings:
        agent_frequency: 200
        discounted_horizon_duration: 0.5
        env_id: UpkieGroundVelocity-v1
        init_pitch_rand: 0.0
        max_episode_duration: 10.0
        max_ground_accel: 10.0
        max_ground_velocity: 1.0
        seed: null
        spine_frequency: 1000
        total_timesteps: 600000.0
        velocity_filter: 0.04
        velocity_filter_rand: null
    PPOSettings:
        batch_size: 64
        clip_range: 0.2
        clip_range_vf: null
        ent_coef: 0.0
        gae_lambda: 0.95
        learning_rate: 0.0003
        max_grad_norm: 0.5
        n_epochs: 10
        n_steps: 2048
        sde_sample_freq: -1
        target_kl: null
        use_sde: false
        vf_coef: 0.5
reward: {}
spine_config:
    bullet:
        control_mode: torque
        follower_camera: false
        gui: true
        position_init_base_in_world:
        - 0.0
        - 0.0
        - 0.6
        torque_control:
            kd: 1.0
            kp: 20.0
    floor_contact:
        upper_leg_torque_threshold: 10.0
    wheel_contact:
        cutoff_period: 0.2
        liftoff_inertia: 0.001
        min_touchdown_acceleration: 2.0
        min_touchdown_torque: 0.015
        touchdown_inertia: 0.004
    wheel_odometry:
        signed_radius:
            left_wheel: 0.05
            right_wheel: -0.05
