env: UpkieGroundVelocity-v1
gin:
    EnvSettings:
        agent_frequency: 200
        env_id: UpkieGroundVelocity-v1
        init_pitch_rand: 0.1
        max_episode_duration: 10.0
        max_ground_accel: 10.0
        max_ground_velocity: 1.0
        return_horizon: 1.0
        seed: null
        sim_torque_control_kd: 0.2
        spine_frequency: 1000
        total_timesteps: 2000000.0
        velocity_filter: null
        velocity_filter_rand: null
    PPOSettings:
        batch_size: 64
        clip_range: 0.1
        clip_range_vf: null
        ent_coef: 0.0
        gae_lambda: 0.95
        learning_rate: 0.0003
        max_grad_norm: 0.5
        n_epochs: 10
        n_steps: 2048
        net_arch_pi: !!python/tuple
        - 16
        - 16
        net_arch_vf: !!python/tuple
        - 32
        - 32
        normalize_advantage: true
        sde_sample_freq: -1
        target_kl: null
        use_sde: false
        vf_coef: 0.5
reward:
    acceleration_penalty_weight: 1.0
spine_config:
    bullet:
        follower_camera: false
        gui: true
        orientation_init_base_in_world: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - &id001 !!python/name:numpy.ndarray ''
            - !!python/tuple
                - 0
            - !!binary |
                Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
                - 4
            - &id002 !!python/object/apply:numpy.dtype
                args:
                - f8
                - false
                - true
                state: !!python/tuple
                - 3
                - <
                - null
                - null
                - null
                - -1
                - -1
                - 0
            - false
            - !!binary |
                iN2BS8D67z8AAAAAAAAAAMCvq3pKU6K/AAAAAAAAAAA=
        position_init_base_in_world: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
                - 0
            - !!binary |
                Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
                - 3
            - *id002
            - false
            - !!binary |
                AAAAAAAAAAAAAAAAAAAAADMzMzMzM+M/
        torque_control:
            kd: 0.2
            kp: 20.0
    floor_contact:
        upper_leg_torque_threshold: 10.0
    wheel_contact:
        cutoff_period: 0.2
        liftoff_inertia: 0.001
        min_touchdown_acceleration: 2.0
        min_touchdown_torque: 0.015
        touchdown_inertia: 0.004
    wheel_odometry:
        signed_radius:
            left_wheel: 0.05
            right_wheel: -0.05
