floor_contact:
    upper_leg_torque_threshold: 10.0
wheel_contact:
    cutoff_period: 0.2
    liftoff_inertia: 0.001
    min_touchdown_acceleration: 2.0
    min_touchdown_torque: 0.015
    touchdown_inertia: 0.004
wheel_odometry:
    signed_radius:
        left_wheel: +0.05
        right_wheel: -0.05
