name: Bazel

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v2

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install numpy

            - name: "Build agents and observers"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk build //...

    coverage:
        name: "Coverage"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v2

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install numpy

            - name: "Report test coverage"
              run: |
                  tools/bazelisk coverage --combined_report=lcov --instrument_test_targets //...

            - name: "Submit report to Coveralls"
              uses: coverallsapp/github-action@1.1.3
              with:
                  github-token: ${{ secrets.github_token }}
                  path-to-lcov: bazel-out/_coverage/_coverage_report.dat

    lint:
        name: "Lint"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v2

            - name: "Check code formatting"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk test --config lint //...

    test:
        name: "Test"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3

            - name: "Set up Python"
              uses: actions/setup-python@v4
              with:
                  python-version: "3.8"

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install numpy six

            - name: "Check unit tests"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk test //...
