name: Documentation

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    docs:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: "Checkout Git repository"
              uses: actions/checkout@v3

            - name: "Install dependencies"
              run: |
                  sudo apt install doxygen inkscape

            - name: "Build documentation"
              run: |
                  cd ${{ github.workspace }}/docs/
                  make html

            - name: "Deploy to GitHub Pages"
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/mmain' }}
              with:
                  publish_branch: gh-pages
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: html/
                  force_orphan: true
