name: PyPI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    pypi:
        name: "Install and import"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v2

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install pin  # TODO(scaron): remove
                  python -m pip install upkie

            - name: "Install PyPI package"
              run: python -m pip install upkie

            - name: "Test module import"
              run: python -c "import upkie"

            - name: "Test submodule imports"
              run: |
                  python -c "import upkie.config"
                  python -c "import upkie.envs"
                  python -c "import upkie.observers"
                  python -c "import upkie.utils"
