name: PyPI install

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    pypi:
        name: "PyPI install"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v2

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install upkie

            - name: "Install PyPI package"
              run: |
                  python -m pip install upkie

            - name: "Test module imports"
              run: |
                  python -c "import upkie"
                  python -c "import upkie.config"
                  python -c "import upkie.envs"
                  python -c "import upkie.observers"
                  python -c "import upkie.utils"
