name: Coverage

on:
    push:
        branches: [ main ]

jobs:
    coverage:
        name: "Coverage"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install numpy pin pin-pink

            - name: "Test coverage"
              run: |
                  tools/bazelisk coverage --combined_report=lcov --compilation_mode=fastbuild --instrument_test_targets //...

            - name: "Submit report to Coveralls"
              uses: coverallsapp/github-action@1.1.3
              with:
                  github-token: ${{ secrets.github_token }}
                  path-to-lcov: ${{ github.workspace }}/bazel-out/_coverage/_coverage_report.dat
